### ISSUE TITLE
Regex exclude of node_modules doesn't seem to work.

### ISSUE THREAD

**Issue by drovani** [merteraslan/Claude-Helper-Web#2]
This extension is exactly what ClaudeAI needs, especially for working with code. So first off - THANK YOU for taking the time to write it. I don't have the expertise to debug my issue, or I'd try to fix it and submit a PR.

I have a React application with ~70 relevant files. There are roughly 170 images files, which I _think_ are being properly excluded.
There there's the node_modules folder... which I just cannot get the app to ignore. This seems to be the case with any folder I try to exclude, including the `.git` folder.

```
^node_modules/
node_modules/.*
node_modules/
```

None of these seem to work.

![image](https://github.com/user-attachments/assets/a0fa8d7b-83b0-4132-aa9d-89a1aeb21663)
![image](https://github.com/user-attachments/assets/74615f69-7020-408f-88d6-4b7c8b232f9d)

v1.4.3

**Comment by merteraslan** [comment]
Hi drovahi, thank you for the kind message. For regex usage you can refer to [Documentation](https://merteraslan.github.io/Claude-Helper-Web/regex_patterns.html) or i icon for the tooltip includes few basic examples for quick access. 

I've tried your regex exclusions and they failed to be excluded on my tests too, however `node_modules/` or `\.git` works for excluding those folders as documented.

Also you shouldn't need to exclude image file extensions, since Claude doesn't support adding pictures as project knowledge they are auto excluded.

Please let me know if I can help further

**Comment by drovani** [comment]
Okay, I see what's happening. I hadn't previously hit "Okay" to the "Upload 18,290 files to this site?" because I thought that was the total number of files that this extension was expecting to push up. I see after the process runs that you display which files were uploaded and which were skipped.
Perhaps slightly better wording could be put in place for that confirmation dialog. Something like "18,290 total files found. Would you like to begin upload to this site, which will then exclude files matching your regex." (it's cumbersome, and that's why I don't work in Marketing 😄)
Alternatively, is it possible to run the regex rules on the files list prior to confirming the number to be uploaded? In my scenario, only 74 files were uploaded.
